class Team(db.Model)
	team_id = db.Column(db.Integer, primary_key = True)
	first_dragon = db.Column(db.Boolean, unique = False, nullable = False)
	game_version = db.Column(db.String(15), unique = False, nullable = False)
	first_inhibitor = db.Column(db.Boolean, unique = False, nullable = False)
	win = db.Column(db.Boolean, unique = False, nullable = False)
	first_baron = db.Column(db.Boolean, unique = False, nullable = False)
	baron_kills = db.Column(db.Integer, unique = False, nullable = False)
	rift_herald_kills = db.Column(db.Integer, unique = False, nullable = False)
	first_blood = db.Column(db.Boolean, unique = False, nullable = False)
	first_tower = db.Column(db.Boolean, unique = False, nullable = False)
	vilemaw_kills = db.Column(db.Integer, unique = False, nullable = False)
	inhibitor_kills = db.Column(db.Integer, unique = False, nullable = False)
	tower_kills = db.Column(db.Integer, unique = False, nullable = False)
	dominion_victory_score = db.Column(db.Integer, unique = False, nullable = False)
	dragon_kills = db.Column(db.Integer, unique = False, nullable = False)